[project]
name = "dw-precos-glp-p13"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lasaro Almeida", email = "lasarodalmeida@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
]

[project.scripts]
dw-precos-glp-p13 = "dw_precos_glp_p13:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
